### ISSUE TITLE
Implement new ReadData constructor for different cases

### ISSUE THREAD

**Issue by stevenhwu** [dwinter/accuMUlate#23]
ReadData should have at least two types of constructor.
1) single uint64_t as key
2) 4 uint14_t as read deapth

**Comment by dwinter** [comment]
Hey @stevenhwu , if this is easy the go for it. Otherwise I can write up a better "test suite" that doesn't need the brace initializers.

**Comment by stevenhwu** [comment]
Almost done, just want to double check before the pull request is created.

**Comment by dwinter** [comment]
Hey @stevenhwu, this is "closed-in-develop" now right?
