### ISSUE TITLE
Only use primary lines by default

### ISSUE THREAD

**Issue by reedacartwright** [dwinter/accuMUlate#33]
From: https://samtools.github.io/hts-specs/SAMv1.pdf

> For each read/contig in a SAM file, it is required that one and only one line associated with the read satisfies `FLAG & 0x900 == 0`  This line is called the primary line of the read.

In the latest Tt run, accuMUlate call SNPs if one of the strains has a `chimeric` alignment. This SAM lines that are part of a chimeric alignment have their 'supplementary alignment' flag set. It is more natural to restrict calls by default to variants supported by primary alignments.

**Comment by dwinter** [comment]
Hi @reedacartwright , I think this one is pretty easy to take care of, will get to it next week.
