### ISSUE TITLE
Deletions being reported as SNPs

### ISSUE THREAD

**Issue by reedacartwright** [dwinter/accuMUlate#34]
In the following situation accuMUlate reports deletions as SNPs (tview-like output):

```
TAC
.*.
.*.
,*,
,*,
```
This is reported as an `A>C` SNP instead of a deletion. I suspect that CIGAR parsing is failing (these lines have hard clipping as well).

**Comment by dwinter** [comment]
Hmmm, that seems like a problem. I can look at it next week, in the meantime can you or @arcova send an example location I can use to test this?

**Comment by arcova** [comment]
@dwinter- sorry to be slow to respond. i've had crappy internet over the weekend. do you just want a .bam or .sam file with info on just that single example site?

**Comment by dwinter** [comment]
Hey @arcova , I think I've worked this out. 

Probably easier if I push the fixed code (once I've added some tests etc) and get you to compile it and run it on your end.
